import type {
  Announcement,
  ChatMessage,
  Guest,
  GuestGroup,
  GuestPhoto,
  GuestbookNote,
  InviteRecord,
  Ride,
  RsvpRecord,
  Side,
  Song,
  StayArea,
  Visibility,
} from "@/lib/hub/types";
import { DEFAULT_GUEST_TAGS } from "@/lib/hub/access";

const DEFAULT_VISIBILITY: Visibility = {
  showInDirectory: true,
  showCity: true,
  showEvents: true,
  allowContact: true,
  showOnLeaderboard: true,
};

type GuestSeed = [
  string,
  string,
  string,
  string,
  Side,
  GuestGroup,
  StayArea | null,
  number,
  boolean,
  boolean,
  boolean,
];

const RAW: GuestSeed[] = [
  ["g1", "Camille", "Fore", "New York, NY", "janelle", "fore-family", "sorrento", 2450, true, false, false],
  ["g2", "David", "Fore", "New York, NY", "janelle", "fore-family", "sorrento", 2200, true, false, true],
  ["g3", "Maya", "Fore", "Brooklyn, NY", "janelle", "fore-family", "naples", 1980, true, false, false],
  ["g4", "Andre", "Fore", "Atlanta, GA", "janelle", "fore-family", "caserta", 1640, false, false, true],
  ["g5", "Simone", "Lewis", "Washington, DC", "janelle", "lewis-family", "naples", 1510, false, false, false],
  ["g6", "James", "Lewis", "Washington, DC", "janelle", "lewis-family", "naples", 980, false, false, true],
  ["g7", "Nia", "Lewis", "Baltimore, MD", "janelle", "lewis-family", "rome", 870, false, false, false],
  ["g8", "Helen", "Walsh", "Boston, MA", "eric", "eric-family", "caserta", 2100, false, false, false],
  ["g9", "Robert", "Walsh", "Boston, MA", "eric", "eric-family", "caserta", 1760, false, false, true],
  ["g10", "Claire", "Walsh", "Cambridge, MA", "eric", "eric-family", "sorrento", 1320, false, false, false],
  ["g11", "Owen", "Walsh", "Providence, RI", "eric", "eric-family", "naples", 640, false, false, false],
  ["g12", "Priya", "Shah", "New York, NY", "both", "nyc", "sorrento", 1880, true, false, false],
  ["g13", "Michael", "Chen", "San Francisco, CA", "janelle", "college", "naples", 1720, false, false, false],
  ["g14", "Sofia", "Rossi", "Rome, Italy", "both", "italy", "rome", 1590, false, true, false],
  ["g15", "Marco", "Bianchi", "Milan, Italy", "eric", "italy", "caserta", 1440, false, true, false],
  ["g16", "Alana", "Brooks", "Los Angeles, CA", "janelle", "friends", "amalfi", 1390, false, false, false],
  ["g17", "Tyler", "Williams", "Miami, FL", "eric", "friends", "naples", 1210, false, false, false],
  ["g18", "Elena", "Marchetti", "Naples, Italy", "both", "italy", "naples", 1180, false, true, false],
  ["g19", "Jordan", "Hale", "Brooklyn, NY", "janelle", "nyc", "villa", 1100, true, false, true],
  ["g20", "Ava", "Okoye", "London, UK", "janelle", "friends", "sorrento", 1040, false, true, false],
  ["g21", "Noah", "Patel", "Chicago, IL", "eric", "college", "rome", 990, false, false, false],
  ["g22", "Leah", "Kim", "New York, NY", "janelle", "nyc", "naples", 940, true, false, false],
  ["g23", "Daniel", "Smith", "Philadelphia, PA", "both", "smith-family", "caserta", 910, false, false, true],
  ["g24", "Grace", "Smith", "Philadelphia, PA", "both", "smith-family", "caserta", 760, false, false, true],
  ["g25", "Isaac", "Smith", "Princeton, NJ", "both", "smith-family", "naples", 520, false, false, false],
  ["g26", "Amara", "Diallo", "Paris, France", "janelle", "friends", "amalfi", 880, false, true, false],
  ["g27", "Luca", "Esposito", "Sorrento, Italy", "both", "italy", "sorrento", 850, false, true, false],
  ["g28", "Hannah", "Cole", "Austin, TX", "eric", "college", "villa", 810, false, false, false],
  ["g29", "Marcus", "Reid", "Atlanta, GA", "janelle", "friends", "naples", 790, false, false, false],
  ["g30", "Isla", "Bennett", "Edinburgh, UK", "eric", "friends", "rome", 740, false, true, false],
  ["g31", "Theo", "Nguyen", "Seattle, WA", "janelle", "college", "sorrento", 710, false, false, false],
  ["g32", "Ruby", "Santos", "Newark, NJ", "janelle", "nyc", "caserta", 690, true, false, false],
  ["g33", "Felix", "Moreau", "Lyon, France", "eric", "friends", "amalfi", 660, false, true, false],
  ["g34", "Zara", "Ahmed", "Toronto, Canada", "janelle", "college", "naples", 630, false, true, false],
  ["g35", "Bennett", "Cole", "New York, NY", "both", "nyc", "villa", 600, true, false, true],
  ["g36", "Chiara", "Romano", "Florence, Italy", "both", "italy", "rome", 570, false, true, false],
  ["g37", "Miles", "Harper", "Denver, CO", "eric", "friends", "naples", 540, false, false, false],
  ["g38", "Naomi", "Brooks", "Los Angeles, CA", "janelle", "friends", "amalfi", 510, false, false, true],
  ["g39", "Adrian", "Perez", "Madrid, Spain", "eric", "friends", "sorrento", 480, false, true, false],
  ["g40", "Lila", "Thompson", "Boston, MA", "eric", "eric-family", "caserta", 450, false, false, false],
  ["g41", "Samuel", "Okeke", "Houston, TX", "janelle", "friends", "naples", 420, false, false, false],
  ["g42", "Freya", "Lind", "Stockholm, Sweden", "both", "friends", "rome", 390, false, true, false],
];

function eventsFor(index: number): Guest["events"] {
  if (index % 11 === 0) return ["ceremony", "reception"];
  if (index % 7 === 0) return ["welcome", "ceremony", "reception"];
  return ["welcome", "ceremony", "reception", "brunch"];
}

export const SEED_GUESTS: Guest[] = RAW.map((row, index) => {
  const [id, firstName, lastName, city, side, group, stay, points, fromNyc, fromAbroad, couple] = row;
  const hidden = id === "g11" || id === "g25";
  return {
    id,
    firstName,
    lastName,
    city,
    side,
    group,
    stay,
    points,
    attending: true,
    fromNyc,
    fromAbroad,
    couple,
    events: eventsFor(index),
    dietary: index % 9 === 0 ? "Vegetarian" : index % 13 === 0 ? "No shellfish" : undefined,
    arrivalAirport: fromAbroad ? "FCO" : "NAP",
    arrivalDate: index % 2 === 0 ? "2027-09-03" : "2027-09-04",
    departureDate: "2027-09-06",
    visibility: {
      ...DEFAULT_VISIBILITY,
      showInDirectory: !hidden,
      showCity: id !== "g30",
      showEvents: id !== "g22",
      allowContact: id !== "g16",
      showOnLeaderboard: id !== "g42",
    },
    avatarHue: (index * 37) % 140,
    joinedAt: `2026-0${(index % 8) + 1}-${String((index % 27) + 1).padStart(2, "0")}T12:00:00.000Z`,
  };
});

const ALL_EVENTS: InviteRecord["events"] = ["welcome", "ceremony", "reception", "brunch"];

export const SEED_INVITES: InviteRecord[] = [
  { id: "inv0", firstName: "Janelle", lastName: "Fore", email: "janelle.fore@example.com", location: "New York, NY", inItaly: false, party: ["Eric"], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv1", firstName: "Camille", lastName: "Fore", email: "camille.fore@example.com", location: "New York, NY", inItaly: false, party: ["David Fore"], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv2", firstName: "Maya", lastName: "Fore", email: "maya.fore@example.com", location: "Brooklyn, NY", inItaly: false, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv3", firstName: "Andre", lastName: "Fore", email: "andre.fore@example.com", location: "Atlanta, GA", inItaly: false, party: ["Guest of Andre Fore"], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv4", firstName: "Simone", lastName: "Lewis", email: "simone.lewis@example.com", location: "Washington, DC", inItaly: false, party: ["James Lewis"], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv5", firstName: "Nia", lastName: "Lewis", email: "nia.lewis@example.com", location: "Baltimore, MD", inItaly: false, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv6", firstName: "Helen", lastName: "Walsh", email: "helen.walsh@example.com", location: "Boston, MA", inItaly: false, party: ["Robert Walsh"], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv7", firstName: "Claire", lastName: "Walsh", email: "claire.walsh@example.com", location: "Cambridge, MA", inItaly: false, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv8", firstName: "Priya", lastName: "Shah", email: "priya.shah@example.com", location: "New York, NY", inItaly: false, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv9", firstName: "Michael", lastName: "Chen", email: "michael.chen@example.com", location: "San Francisco, CA", inItaly: false, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv10", firstName: "Sofia", lastName: "Rossi", email: "sofia.rossi@example.com", location: "Rome, Italy", inItaly: true, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv11", firstName: "Marco", lastName: "Bianchi", email: "marco.bianchi@example.com", location: "Milan, Italy", inItaly: true, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv12", firstName: "Alana", lastName: "Brooks", email: "alana.brooks@example.com", location: "Los Angeles, CA", inItaly: false, party: ["Naomi Brooks"], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv13", firstName: "Tyler", lastName: "Williams", email: "tyler.williams@example.com", location: "Miami, FL", inItaly: false, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv14", firstName: "Elena", lastName: "Marchetti", email: "elena.marchetti@example.com", location: "Naples, Italy", inItaly: true, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv15", firstName: "Jordan", lastName: "Hale", email: "jordan.hale@example.com", location: "Brooklyn, NY", inItaly: false, party: ["Bennett Cole"], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv16", firstName: "Ava", lastName: "Okoye", email: "ava.okoye@example.com", location: "London, UK", inItaly: false, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv17", firstName: "Daniel", lastName: "Smith", email: "daniel.smith@example.com", location: "Philadelphia, PA", inItaly: false, party: ["Grace Smith"], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv18", firstName: "Luca", lastName: "Esposito", email: "luca.esposito@example.com", location: "Sorrento, Italy", inItaly: true, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv19", firstName: "Chiara", lastName: "Romano", email: "chiara.romano@example.com", location: "Florence, Italy", inItaly: true, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
  { id: "inv20", firstName: "Hannah", lastName: "Cole", email: "hannah.cole@example.com", location: "Austin, TX", inItaly: false, party: [], events: ALL_EVENTS, tags: [...DEFAULT_GUEST_TAGS] },
];

export const SEED_RSVPS: RsvpRecord[] = [
  {
    id: "rsvp1",
    name: "Camille Fore",
    email: "camille.fore@example.com",
    attending: true,
    events: ["welcome", "ceremony", "reception", "brunch"],
    guestCount: 2,
    dietary: "",
    song: "",
    airport: "NAP",
    arrivalDate: "2027-09-04",
    arrivalTime: "14:00",
    departureDate: "2027-09-07",
    departureTime: "11:00",
    stay: "sorrento",
    inviteId: "inv1",
    partyAttending: ["Camille Fore", "David Fore"],
    submittedAt: "2026-08-12T12:00:00.000Z",
  },
  {
    id: "rsvp2",
    name: "Sofia Rossi",
    email: "sofia.rossi@example.com",
    attending: true,
    events: ["ceremony", "reception"],
    guestCount: 1,
    dietary: "Vegetarian",
    song: "",
    airport: "",
    arrivalDate: "",
    arrivalTime: "",
    departureDate: "",
    departureTime: "",
    stay: "rome",
    inviteId: "inv10",
    partyAttending: ["Sofia Rossi"],
    submittedAt: "2026-08-18T12:00:00.000Z",
  },
  {
    id: "rsvp3",
    name: "Helen Walsh",
    email: "helen.walsh@example.com",
    attending: true,
    events: ["welcome", "ceremony", "reception", "brunch"],
    guestCount: 2,
    dietary: "",
    song: "",
    airport: "FCO",
    arrivalDate: "2027-09-03",
    arrivalTime: "10:30",
    departureDate: "2027-09-07",
    departureTime: "16:00",
    stay: "caserta",
    inviteId: "inv6",
    partyAttending: ["Helen Walsh", "Robert Walsh"],
    submittedAt: "2026-08-20T12:00:00.000Z",
  },
  {
    id: "rsvp4",
    name: "Tyler Williams",
    email: "tyler.williams@example.com",
    attending: false,
    events: [],
    guestCount: 0,
    dietary: "",
    song: "",
    airport: "",
    arrivalDate: "",
    arrivalTime: "",
    departureDate: "",
    departureTime: "",
    stay: "",
    inviteId: "inv13",
    partyAttending: [],
    submittedAt: "2026-08-22T12:00:00.000Z",
  },
  {
    id: "rsvp5",
    name: "Hannah Cole",
    email: "hannah.cole@example.com",
    attending: false,
    events: [],
    guestCount: 0,
    dietary: "",
    song: "",
    airport: "",
    arrivalDate: "",
    arrivalTime: "",
    departureDate: "",
    departureTime: "",
    stay: "",
    inviteId: "inv20",
    partyAttending: [],
    submittedAt: "2026-08-25T12:00:00.000Z",
  },
];

export const SEED_RIDES: Ride[] = [
  {
    id: "r1",
    kind: "offer",
    authorId: "g17",
    from: "Naples Airport (NAP)",
    to: "Casale dei Mascioni",
    date: "2027-09-04",
    time: "15:00",
    seats: 3,
    seatsTaken: 1,
    luggage: "3 large bags",
    notes: "Rental car. Happy to detour through Caserta if it helps.",
    status: "open",
  },
  {
    id: "r2",
    kind: "request",
    authorId: "g12",
    from: "Naples Airport (NAP)",
    to: "Sorrento",
    date: "2027-09-04",
    time: "12:00",
    seats: 2,
    seatsTaken: 0,
    luggage: "2 large bags",
    notes: "Landing NAP 11:10. Flexible on exact hotel drop.",
    status: "open",
  },
  {
    id: "r3",
    kind: "offer",
    authorId: "g15",
    from: "Napoli Centrale",
    to: "Casale dei Mascioni",
    date: "2027-09-03",
    time: "16:30",
    seats: 2,
    seatsTaken: 2,
    luggage: "2 cabin bags",
    notes: "Driving from Milan that morning.",
    status: "full",
  },
  {
    id: "r4",
    kind: "offer",
    authorId: "g8",
    from: "Grand Hotel Vesuvio",
    to: "Casale dei Mascioni",
    date: "2027-09-05",
    time: "15:00",
    seats: 3,
    seatsTaken: 0,
    luggage: "None — wedding only",
    notes: "Wedding day car. Returning after last shuttle if needed.",
    status: "open",
  },
  {
    id: "r5",
    kind: "request",
    authorId: "g20",
    from: "Rome Fiumicino (FCO)",
    to: "Naples hotels",
    date: "2027-09-03",
    time: "10:30",
    seats: 1,
    seatsTaken: 0,
    luggage: "1 large bag",
    notes: "Can also take the train — looking for company more than a seat.",
    status: "pending",
  },
  {
    id: "r6",
    kind: "offer",
    authorId: "g14",
    from: "Roma Termini",
    to: "Napoli Centrale",
    date: "2027-09-04",
    time: "09:20",
    seats: 4,
    seatsTaken: 1,
    luggage: "Frecciarossa tickets already held",
    notes: "I reserved a four-seat table. Join the train, not a car.",
    status: "open",
  },
];

export const SEED_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    channel: "general",
    authorId: "g2",
    body: "We just booked the last rooms in our Naples block — if you're still hunting, San Francesco al Monte still had availability yesterday.",
    createdAt: "2026-08-20T14:12:00.000Z",
    hearts: ["g12", "g13", "g22"],
  },
  {
    id: "m2",
    channel: "travel",
    authorId: "g17",
    body: "Offering 2 seats from NAP on Sept 4 at 3pm. Car is a compact SUV so bags are welcome.",
    createdAt: "2026-08-22T09:40:00.000Z",
    hearts: ["g12", "g20"],
  },
  {
    id: "m3",
    channel: "italy",
    authorId: "g18",
    body: "If you only do one lunch in Naples: da Michele, then walk it off through Spaccanapoli. Don't book Friday night restaurants last-minute.",
    createdAt: "2026-08-24T18:02:00.000Z",
    hearts: ["g14", "g15", "g16", "g27", "g3"],
  },
  {
    id: "m4",
    channel: "weekend",
    authorId: "g1",
    body: "Reminder from the family side: welcome dinner is Saturday the 5th. Shuttle details will land in Updates next month.",
    createdAt: "2026-08-26T11:15:00.000Z",
    hearts: ["g8", "g12"],
  },
  {
    id: "m5",
    channel: "afterparty",
    authorId: "g16",
    body: "Whoever is still standing after dancing: Sorrento terrace spritzes on Sunday afternoon. Who's in?",
    createdAt: "2026-08-28T21:08:00.000Z",
    hearts: ["g19", "g35", "g27"],
  },
  {
    id: "m6",
    channel: "general",
    authorId: "g13",
    body: "Just finished the How Well Do You Know Us quiz. I thought I knew them. I did not.",
    createdAt: "2026-08-29T16:44:00.000Z",
    hearts: ["g12", "g16"],
  },
];

export const SEED_GUESTBOOK: GuestbookNote[] = [
  {
    id: "gb1",
    authorId: "g12",
    authorName: "Priya S.",
    body: "Wishing you both a lifetime of adventures, laughter, and love — and excellent pasta.",
    createdAt: "2026-07-12T10:00:00.000Z",
    hearts: ["g1", "g2", "g8", "g16"],
  },
  {
    id: "gb2",
    authorId: "g8",
    authorName: "Helen W.",
    body: "Eric has talked about this day since he was small. Janelle, you are the best thing that ever happened to our family.",
    createdAt: "2026-07-20T15:30:00.000Z",
    hearts: ["g9", "g10", "g1"],
  },
  {
    id: "gb3",
    authorId: "g14",
    authorName: "Sofia R.",
    body: "Benvenuti a casa. Italy already loves you — now we get to celebrate you here.",
    createdAt: "2026-08-02T09:12:00.000Z",
    hearts: ["g15", "g18", "g27"],
  },
  {
    id: "gb4",
    authorId: "g13",
    authorName: "Michael C.",
    body: "Marriage advice: keep the Sunday pasta tradition. Protect it like a holiday.",
    createdAt: "2026-08-14T19:45:00.000Z",
    hearts: ["g3", "g12", "g16", "g22"],
  },
];

export const SEED_SONGS: Song[] = [
  { id: "s1", title: "September", artist: "Earth, Wind & Fire", category: "classics", suggestedBy: "Camille F.", approved: true, ups: ["g1", "g2", "g12", "g13", "g16", "g17", "g22", "g35"], downs: [] },
  { id: "s2", title: "Crazy in Love", artist: "Beyoncé", category: "2000s", suggestedBy: "Priya S.", approved: true, ups: ["g12", "g3", "g22", "g16", "g19"], downs: [] },
  { id: "s3", title: "On the Floor", artist: "Jennifer Lopez", category: "2000s", suggestedBy: "Alana B.", approved: true, ups: ["g16", "g17", "g26"], downs: ["g8"] },
  { id: "s4", title: "Love on the Brain", artist: "Rihanna", category: "rnb", suggestedBy: "Leah K.", approved: true, ups: ["g22", "g12", "g3", "g38"], downs: [] },
  { id: "s5", title: "Temperature", artist: "Sean Paul", category: "dancehall", suggestedBy: "Marcus R.", approved: true, ups: ["g29", "g17", "g41", "g4"], downs: [] },
  { id: "s6", title: "Love Nwantiti", artist: "CKay", category: "afrobeats", suggestedBy: "Amara D.", approved: true, ups: ["g26", "g41", "g16", "g12", "g22"], downs: [] },
  { id: "s7", title: "Tu Vuò Fà L'Americano", artist: "Renato Carosone", category: "italian", suggestedBy: "Elena M.", approved: true, ups: ["g18", "g14", "g15", "g27"], downs: [] },
  { id: "s8", title: "This Is How We Do It", artist: "Montell Jordan", category: "90s", suggestedBy: "Tyler W.", approved: true, ups: ["g17", "g13", "g28"], downs: [] },
  { id: "s9", title: "Mr. Brightside", artist: "The Killers", category: "guilty", suggestedBy: "Hannah C.", approved: true, ups: ["g28", "g31", "g37", "g13", "g19"], downs: ["g5"] },
  { id: "s10", title: "No One", artist: "Alicia Keys", category: "rnb", suggestedBy: "Simone L.", approved: true, ups: ["g5", "g6", "g1"], downs: [] },
  { id: "s11", title: "Then", artist: "Brad Paisley", category: "classics", suggestedBy: "Guest", approved: false, ups: [], downs: [] },
];

export const SEED_PHOTOS: GuestPhoto[] = [
  { id: "p1", authorId: "g14", album: "travel", caption: "First light over the coast", src: "/images/amalfi-coast.jpg", approved: true, createdAt: "2026-08-10T08:00:00.000Z" },
  { id: "p2", authorId: "g27", album: "travel", caption: "Sorrento, last September", src: "/images/sorrento.jpg", approved: true, createdAt: "2026-08-11T12:00:00.000Z" },
  { id: "p3", authorId: "g18", album: "travel", caption: "Naples doing what Naples does", src: "/images/naples.jpg", approved: true, createdAt: "2026-08-12T16:00:00.000Z" },
  { id: "p4", authorId: "g1", album: "recent", caption: "The estate that started it", src: "/images/casale-mascioni.jpg", approved: true, createdAt: "2026-08-18T10:00:00.000Z" },
  { id: "p5", authorId: "g16", album: "recent", caption: "Caserta gardens", src: "/images/caserta.jpg", approved: true, createdAt: "2026-08-19T14:00:00.000Z" },
  { id: "p6", authorId: "g13", album: "travel", caption: "Rome extension, highly recommended", src: "/images/rome.jpg", approved: true, createdAt: "2026-08-21T09:00:00.000Z" },
  { id: "p7", authorId: "g3", album: "recent", caption: "Waiting for the weekend", src: "/images/venue-estate.jpg", approved: true, createdAt: "2026-08-25T11:00:00.000Z" },
  { id: "p8", authorId: "g20", album: "friday", caption: "Pending moderation", src: "/images/travel-landscape.jpg", approved: false, createdAt: "2026-08-28T18:00:00.000Z" },
];

export const SEED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "a1",
    title: "Welcome to the wedding hub",
    body: "This site is yours for the year. RSVP when you're ready, join the community when you want to play, and check back — we'll keep adding details.",
    category: "general",
    publishedAt: "2026-06-01T12:00:00.000Z",
  },
  {
    id: "a2",
    title: "Hotel blocks are opening",
    body: "Preferred rates at Grand Hotel Vesuvio and San Francesco al Monte will be posted here. Book refundable fares in the meantime if you're flying transatlantic.",
    category: "hotel",
    publishedAt: "2026-07-15T12:00:00.000Z",
  },
  {
    id: "a3",
    title: "Shuttle planning has started",
    body: "We're arranging coaches between Naples hotels and the estate for Saturday dinner and Sunday. Exact pickup times will be published 6 weeks out.",
    category: "transport",
    publishedAt: "2026-08-10T12:00:00.000Z",
  },
];

export const DEFAULT_VIS = DEFAULT_VISIBILITY;
